---
- name: Install kubernetes
  ansible.builtin.import_tasks: install_kubernetes.yml
  tags: install

- name: Install ha
  ansible.builtin.import_tasks: install_ha.yml
  when: k8s_ha_cluster_virtual_ip != ""
  tags: install_ha

- name: Start first control node
  ansible.builtin.import_tasks: start_master.yml
  run_once: true
  tags: master

- name: Join nodes to kubernetes cluster
  ansible.builtin.import_tasks: join_nodes.yml
  tags: join
